# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 4.0.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
